### ISSUE TITLE
missing Port1 ip address

### ISSUE THREAD

**Issue by nbctcp** [skippernl/Fortigate2Excel#7]
Thank you for your wonderful tool
I have few questions
1. I prefer my timezone as in config but if I didn't rename TimeZones.csv there, it will change to "(GMT-8:00) Pacific Time (US & Canada)"
because of that I need to rename TimeZones.csv
2. what is the function of ISDB-Fortigate.csv
3. I can't find my port1 ip address.
I think ip address is important
Could you please add that feature in the next release
tq

**Comment by skippernl** [comment]
Hi,

Thanx

The purpose of both csv files is to display names instead of numbers.

Remove the timezone csv and you have the desired result.

The second csv is a export of the fortigate service database.

Can you give a sanitized copy of the port1 section so I  can take a look.

SkipperNL

Op di 20 okt. 2020 13:15 schreef nbctcp <notifications@github.com>:

**Comment by nbctcp** [comment]
Here the full config file

#removed configfile

**Comment by skippernl** [comment]
Hi,

I have updated the script. You are using a full export and the script has not been tested with IPV6 Settings. That should be better now.

Please close the issue if you think it is fixed

**Comment by nbctcp** [comment]
no need to delete TimeZones.csv and TImeZones.csv
now my timezone correct and port ip appear
tq
